### ISSUE TITLE
Error when loading.

### ISSUE THREAD

**Issue by flaxues** [zzm317/ZMusicBox#1]
[WARNING]: RuntimeException: "Division by zero" (E_WARNING) in "/ZMusicBox-1.12.1/src/ZMusicBox/ZMusicBox" at line 70

With latest release.

**Comment by zzm317** [comment]
==check your yml file

**Comment by flaxues** [comment]
Which one?

**Comment by flaxues** [comment]
Nvm i found it how can i make my own music is there any program for that?

**Comment by zzm317** [comment]
I will update the support for nbs later
