### ISSUE TITLE
Sounds are playing slow

### ISSUE THREAD

**Issue by poustmal** [zzm317/ZMusicBox#12]
Running software:Clearsky version 8521832b
Plugin version:902cbd6
When I placed a noteblock to start playing musics,they're playing slow.I restarted the server and I had the same result.

**Comment by zzm317** [comment]
ok,I'll try to fix it

**Comment by poustmal** [comment]
ok.

**Comment by TheRoyalBlock** [comment]
fixed yet?

**Comment by poustmal** [comment]
I found the problem!The tempo is 3000,should be 2990.Even i dont know about developing,i found solution,lol

**Comment by TheRoyalBlock** [comment]
Really? Awesome!
