### ISSUE TITLE
1.0 Update

### ISSUE THREAD

**Issue by MalakasPlayzMC** [zzm317/ZMusicBox#14]
I have tried to play a song in 1.0 and it wasn't working. I heard only some sounds sometimes. I use Tesseract for 1.0.3. Please fix it

**Comment by poustmal** [comment]
Its pocketmine's problem,(noteblocks don't work).geia,lol.

**Comment by MalakasPlayzMC** [comment]
OK, thanks
Btw, Geia

**Comment by SuperXingKong** [comment]
@poustmal How soon will it be fixed?

**Comment by poustmal** [comment]
We should all wait pocketmine to fix noteblocks and then plugin will start working again,idk.

**Comment by SalmonDE** [comment]
@poustmal You don't need to. This plugin already uses packets, it doesn't need anything more. As you can see in my little fork [here](https://github.com/SalmonDE/ZMusicBox) I just had to make a few edits.
My fork works with the [api3/network branch](https://github.com/pmmp/PocketMine-MP/tree/api3/network) of pmmp.

![image](https://cloud.githubusercontent.com/assets/15953947/25070589/f5dfac52-22a2-11e7-960b-b54f3d64e101.png)

**Comment by poustmal** [comment]
ok

**Comment by SalmonDE** [comment]
@poustmal Are they lagging the server or the client? I can't observe any signs of lags with ZMusicBox.

**Comment by poustmal** [comment]
I think that they lagging the client because when i removed them (not plugin,i mean the blocks) lagg disappears.
