### ISSUE TITLE
Question:

### ISSUE THREAD

**Issue by TheRoyalBlock** [zzm317/ZMusicBox#16]
Are multiple noteblocks supported so that players can hear music anywhere (it would be the same music because it is all operated by one command, right)?

**Comment by zzm317** [comment]
yes

**Comment by zzm317** [comment]
the plugin will foreach the blocks near the player so if a noteblock is near him，he will hear the music

**Comment by TheRoyalBlock** [comment]
Thank you!

**Comment by SuperXingKong** [comment]
@TheRoyalBlock Can you hear the sound?I use Tesseract, but I can't hear anything.

**Comment by TheRoyalBlock** [comment]
Haven't tested...
