### ISSUE TITLE
Cant hear sound 

### ISSUE THREAD

**Issue by minlack0189** [zzm317/ZMusicBox#19]
i can not hear sound in game

**Comment by TheRoyalBlock** [comment]
make sure that your volume is turned on, and make sure that the server software that you are using supports noteblocks. The softwares with noteblock support are Tesseract, BlueLight. Pocketmine-MP does not have noteblock support.

**Comment by huybinh2009** [comment]
im using tesseract

**Comment by minlack0189** [comment]
im using teseract

**Comment by MalakasPlayzMC** [comment]
Use this: https://github.com/FreeGamingHere/ZMusicBox

**Comment by MalakasPlayzMC** [comment]
I have tested with BlueLight and it worked
