### ISSUE TITLE
Not working anymore (1.1.0)

### ISSUE THREAD

**Issue by arsenicblast** [zzm317/ZMusicBox#21]
09:57:34 [CRITICAL] Could not execute task ZMusicBox\MusicPlayer: Argument 1 passed to pocketmine\Player::dataPacket() must be an instance of pocketmine\network\mcpe\protocol\DataPacket, instance of pocketmine\network\protocol\BlockEventPacket given, called in C:\Users\lenovo\Documents\PocketMine-MP\plugins\ZMusicBox-master\src\ZMusicBox\ZMusicBox.php on line 199
09:57:34 [CRITICAL] TypeError: "Argument 1 passed to pocketmine\Player::dataPacket() must be an instance of pocketmine\network\mcpe\protocol\DataPacket, instance of pocketmine\network\protocol\BlockEventPacket given, called in C:\Users\lenovo\Documents\PocketMine-MP\plugins\ZMusicBox-master\src\ZMusicBox\ZMusicBox.php on line 199" (EXCEPTION) in "/src/pocketmine/Player" at line 1071

**Comment by poustmal** [comment]
You can use this(you should convert it to phar file using the devtools plugin):https://github.com/WakeUpPocketmine/ZMusicBox/archive/master.zip

**Comment by TheRoyalBlock** [comment]
Try again, it has been merged into master.
