### ISSUE TITLE
it not work

### ISSUE THREAD

**Issue by Emis02** [zzm317/ZMusicBox#22]
Thanks to me on genisysPro the sound blocks make noise but with its plugin they do not reproduce any song

**Comment by SuperKali** [comment]
@Emis02 
IT: certo che non rispoduce il sound è fatto appositamente per pmmp
EN: Sure does not play the sound is done specifically for pmmp

**Comment by TheRoyalBlock** [comment]
That is true, The plugin is developed for PocketMine-MP, and only PocketMine-MP, not third-party-spoons. If you would like, feel free to add a pull request that adds the functionality for both PocketMine-MP and the spoons, but it **must** have Pmmp compatibility.
