### ISSUE TITLE
Make no sense

### ISSUE THREAD

**Issue by Thunder33345** [zzm317/ZMusicBox#3]
"use the codes inside to sell money" quoted form readme.md
How?
make no sense
like i will sell you money if you email me that code that is publicily avable
PS if you dont want someone to make money off your stuff dont put it here sadly that just how the world works

**Comment by zzm317** [comment]
just means 
copy the codes and use it in other plugins which is not open-source and is encoded(or not encoded) to sell for money

**Comment by zzm317** [comment]
And forgive my poor english! XD
