### ISSUE TITLE
I put it in and use plugins failed

### ISSUE THREAD

**Issue by Vietnamese02** [zzm317/ZMusicBox#6]
Help me !!!

**Comment by zzm317** [comment]
what do you men？

**Comment by Blubberboy333** [comment]
Hey @Vietnamese02 developers can't help you if they don't know what the problem is. Try to elaborate a little bit more so that @zzm317 can understand your issue

**Comment by Vietnamese02** [comment]
I had one of the songs on the game .nbs and I / music song name and it does not work

**Comment by Vietnamese02** [comment]
Please guide me - help

**Comment by zzm317** [comment]
please use other language if you cann't use english well

**Comment by zzm317** [comment]
any crash report?

**Comment by zzm317** [comment]
nbs files should be put in folder called songs
and did the plugin print "§bPlease put in nbs files!!!"?

**Comment by thebigsmileXD** [comment]
![image](https://cloud.githubusercontent.com/assets/8733998/16541194/9c45e570-407c-11e6-967e-23fa87cb3dff.png)
I have a nbs file in /plugins/ZMusicBox/songs, but it did print an error

**Comment by Thecraftdu34** [comment]
Put the nbs file in "songs" folder in the folder  "plugins" not in the src of this plugin

**Comment by thebigsmileXD** [comment]
Oh, thats a bit conusng, but atleast it does not show "put files" anymore

**Comment by thebigsmileXD** [comment]
now i instantly get an unpack error.
![image](https://cloud.githubusercontent.com/assets/8733998/16541247/051285e4-407e-11e6-902a-6b808ab9e74b.png)

**Comment by zzm317** [comment]
=-=interesting

**Comment by NeuroBinds** [comment]
Its Work Fine For Me.

**Comment by thebigsmileXD** [comment]
My system does not support chinese lkanguage, thats the problem.
