### ISSUE TITLE
Commands doesn't work

### ISSUE THREAD

**Issue by Thecraftdu34** [zzm317/ZMusicBox#7]
Hello, command /music doesn't work. 

Server said "Unknow command..."

**Comment by zzm317** [comment]
Usage:/music <next>

**Comment by Thecraftdu34** [comment]
Yeah i know it but command /music doesn't exist And in /help She is not listed.

**Comment by zzm317** [comment]
=-=prehaps i forget to add it
but did /music next work?

**Comment by Thecraftdu34** [comment]
No She doesn't

**Comment by zzm317** [comment]
fixed

**Comment by zzm317** [comment]
try it \(=_=\)

**Comment by Thecraftdu34** [comment]
Thanks a lot ! 😃

**Comment by zzm317** [comment]
can you try the latest update and tell me if it is grearer?

**Comment by Thecraftdu34** [comment]
Yup ! It's better

**Comment by Thecraftdu34** [comment]
Error: "Call to undefined function ZMusicBox\iconv()" (EXCEPTION) in "/phar_ZMusicBox-master_CabzUkIzpOzyufw.phar/src/ZMusicBox/ZMusicBox" music
