### ISSUE TITLE
New update doesn't work.

### ISSUE THREAD

**Issue by Thecraftdu34** [zzm317/ZMusicBox#8]
Error: "Call to undefined function ZMusicBox\iconv()" (EXCEPTION) in "/phar_ZMusicBox-master_CabzUkIzpOzyufw.phar/src/ZMusicBox/ZMusicBox"

**Comment by zzm317** [comment]
did you compile iconv into php？

**Comment by zzm317** [comment]
just compile iconv into php or add extension in php.ini

**Comment by Thecraftdu34** [comment]
I use http://pmt.mcpe.me/pocketmine.php to compile

**Comment by zzm317** [comment]
i mean your bin not my plugin
and plugin is not called compile i think
it should be called pack i guess

**Comment by zzm317** [comment]
http://php.net/manual/en/book.iconv.php

**Comment by Thecraftdu34** [comment]
I don't understand how i can fix this :c

**Comment by zzm317** [comment]
win or linux？

**Comment by Thecraftdu34** [comment]
Ubuntu  so it's linux

**Comment by zzm317** [comment]
how did you co m pi le your bin？

**Comment by Thecraftdu34** [comment]
bin = source?

**Comment by zzm317** [comment]
。。。
the bin folder in pm's folder

**Comment by zzm317** [comment]
try the fixed ver
