### ISSUE TITLE
It doesnt work for me :(

### ISSUE THREAD

**Issue by ImSilencer** [zzm317/ZMusicBox#9]
Can you show me step-by-step how to use the plugin? I used DevTools to /makeplugin and paste the ZMusicBox.phar to /plugins, and it reported the error:
![untitled](https://cloud.githubusercontent.com/assets/16950680/16677696/8cd41690-4502-11e6-9dce-28f26d09875e.png)

**Comment by zzm317** [comment]
use this

**Comment by zzm317** [comment]
https://github.com/zzm317/ZMusicBox/blob/master/phar/ZMusicBox_v2.6.0.phar

**Comment by ImSilencer** [comment]
Ill try, thanks
